# Generated by Django 3.0.6 on 2020-05-13 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_tarefa',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
